version: '3.9'

services:
    app:
        build: .
        ports:
            - '8081:8080'
        depends_on:
            - db
        deploy:
            resources:
                limits:
                    memory: 512M
                    cpus: 0.50
                reservations:
                    memory: 256M
                    cpus: 0.25

    db:
        image: postgres:15-alpine # Using the Alpine version for smaller size
        ports:
            - '4444:5432'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
            POSTGRES_DB: myapp_db # Added default database name
        volumes:
            - postgres_data:/var/lib/postgresql/data # Persistent volume for data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 5s
            timeout: 5s
            retries: 5
        deploy:
            resources:
                limits:
                    memory: 1G
                    cpus: 1.0
                reservations:
                    memory: 512M
                    cpus: 0.5

volumes:
    postgres_data:
