version: '3.9'

services:
  app:  # Renamed from "deploy" to a valid service name
    build: .
    ports:
      - "8081:8080"
    deploy:  # Moved "deploy" under the service
      resources:
        limits:
          memory: 512M
          cpus: 0.50
        reservations:
          memory: 256M
          cpus: 0.25

  db:
    image: postgres
    ports:
      - '4444:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root