-- AlterTable
ALTER TABLE "Categoria" ALTER COLUMN "createDate" SET DATA TYPE TIMESTAMP(0),
ALTER COLUMN "endDate" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Contato" ALTER COLUMN "creatDate" SET DATA TYPE TIMESTAMP(0),
ALTER COLUMN "endDate" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Transacao" ALTER COLUMN "createDate" SET DATA TYPE TIMESTAMP(0),
ALTER COLUMN "endDate" SET DATA TYPE TIMESTAMP(0);
